---
- name: 'Reload systemd daemon'
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: 'Restart chrony service'
  ansible.builtin.systemd_service:
    name: 'chrony.service'
    state: 'restarted'

- name: 'Restart postfix service'
  ansible.builtin.systemd_service:
    name: 'postfix.service'
    state: 'restarted'

- name: 'Reload nut-monitor service'
  ansible.builtin.systemd_service:
    name: 'nut-monitor.service'
    state: 'reloaded'

- name: 'Postmap sasl_passwd' # noqa: no-changed-when
  ansible.builtin.command:
    cmd: 'postmap /etc/postfix/sasl_passwd'

- name: 'Postmap smtp_header_checks' # noqa: no-changed-when
  ansible.builtin.command:
    cmd: 'postmap /etc/postfix/smtp_header_checks'

- name: 'Postmap canonical' # noqa: no-changed-when
  ansible.builtin.command:
    cmd: 'postmap /etc/postfix/canonical'
