---
- name: 'Configure OS'
  when: (containers_list is not defined)
  tags: ['os-setup']
  block:
    - name: 'Install packages'
      ansible.builtin.import_tasks: 'packages.yml'

    # - name: 'Configure PAM'
    #   ansible.builtin.import_tasks: 'pam.yml'

    - name: 'Configure firewalld'
      ansible.builtin.import_tasks: 'firewalld.yml'

    - name: 'Configure fail2ban'
      ansible.builtin.import_tasks: 'fail2ban.yml'

    - name: 'Configure wireguard'
      ansible.builtin.import_tasks: 'wireguard.yml'
      when: ("remote_gateways" in group_names)

    # - name: 'Configure SMTP'
    #   ansible.builtin.import_tasks: 'smtp.yml'
