---
- name: 'Create/Update Overseerr CNAME record'
  community.general.cloudflare_dns:
    api_token: '{{ cloudflare_dns_token }}'
    zone: '{{ domain_name }}'
    record: 'overseerr'
    ttl: 3600
    type: 'CNAME'
    value: '{{ ansible_facts["fqdn"] }}'
    proxied: false
    state: 'present'
  delegate_to: 'localhost'

- name: 'Create Overseerr data bind mount path'
  ansible.builtin.file:
    path: '{{ containers_storage_path }}/data/overseerr'
    owner: 'root'
    group: 'root'
    mode: '0700'
    state: 'directory'

- name: 'Create Overseerr quadlet unit from template'
  ansible.builtin.template:
    src: 'overseerr.container.j2'
    dest: '/etc/containers/systemd/overseerr.container'
    owner: 'root'
    group: 'root'
    mode: '0644'
  register: 'quadlet_unit'
  notify: 'Reload systemd daemon'

- name: 'Enable and start Overseerr container'
  ansible.builtin.systemd_service:
    name: 'overseerr.service'
    daemon_reload: true
    enabled: true
    state: 'started'
  register: 'systemd_start'

- name: 'Restart Overseerr service if quadlet unit has changed while service was already started'
  ansible.builtin.systemd_service:
    name: 'overseerr.service'
    daemon_reload: true
    state: 'restarted'
  when: (quadlet_unit.changed and not systemd_start.changed)
