---
- name: 'Create/Update Stirling PDF CNAME record'
  community.general.cloudflare_dns:
    api_token: '{{ cloudflare_dns_token }}'
    zone: '{{ domain_name }}'
    record: 'pdf'
    ttl: 3600
    type: 'CNAME'
    value: '{{ ansible_fqdn }}'
    proxied: false
    state: 'present'
  delegate_to: 'localhost'

- name: 'Create Stirling PDF quadlet unit from template'
  ansible.builtin.template:
    src: 'stirling-pdf.container.j2'
    dest: '/etc/containers/systemd/stirling-pdf.container'
    owner: 'root'
    group: 'root'
    mode: '0644'
  register: 'quadlet_unit'
  notify: 'Reload systemd daemon'

- name: 'Enable and start Stirling PDF container'
  ansible.builtin.systemd_service:
    name: 'stirling-pdf.service'
    daemon_reload: true
    enabled: true
    state: 'started'
  register: 'systemd_start'

- name: 'Restart Stirling PDF service if quadlet unit has changed while service was already started'
  ansible.builtin.systemd_service:
    name: 'stirling-pdf.service'
    daemon_reload: true
    state: 'restarted'
  when: (quadlet_unit.changed and not systemd_start.changed)
