---
- name: 'Create/Update Navidrome CNAME record'
  community.general.cloudflare_dns:
    api_token: '{{ cloudflare_dns_token }}'
    zone: '{{ domain_name }}'
    record: 'navidrome'
    ttl: 3600
    type: 'CNAME'
    value: '{{ ansible_fqdn }}'
    proxied: false
    state: 'present'
  delegate_to: 'localhost'

- name: 'Create Navidrome data bind mount path'
  ansible.builtin.file:
    path: '{{ containers_storage_path }}/data/navidrome'
    owner: 1000
    group: 1000
    mode: '0700'
    state: 'directory'

- name: 'Create Navidrome quadlet unit from template'
  ansible.builtin.template:
    src: 'navidrome.container.j2'
    dest: '/etc/containers/systemd/navidrome.container'
    owner: 'root'
    group: 'root'
    mode: '0644'
  register: 'quadlet_unit'
  notify: 'Reload systemd daemon'

- name: 'Enable and start Navidrome container'
  ansible.builtin.systemd_service:
    name: 'navidrome.service'
    daemon_reload: true
    enabled: true
    state: 'started'
  register: 'systemd_start'

- name: 'Restart Navidrome service if quadlet unit has changed while service was already started'
  ansible.builtin.systemd_service:
    name: 'navidrome.service'
    daemon_reload: true
    state: 'restarted'
  when: (quadlet_unit.changed and not systemd_start.changed)
