---
containers_images:
  healthchecks:
    postgres: 'public.ecr.aws/docker/library/postgres'
    server: 'docker.io/healthchecks/healthchecks'
containers_images_tags:
  healthchecks:
    postgres: 'latest'
    server: 'latest'
