---
- name: 'Pull rsync-servers image'
  containers.podman.podman_image:
    name: '{{ containers_images.rsync_servers }}:{{ containers_images_tags.rsync_servers }}'
    pull: true
    force: true
    state: 'present'
  register: 'container_image_pull'
  tags: ['never', 'containers-pull', 'containers-update']

- name: 'Update rsync-servers tag in systemd unit and scripts' # noqa: no-handler
  ansible.builtin.template:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    owner: 'root'
    group: 'root'
    mode: '{{ item.mode }}'
  loop:
    - src: 'rsync-servers.service.j2'
      dest: '/etc/systemd/system/rsync-servers.service'
      mode: '0644'
    - src: 'rsync-servers.j2'
      dest: '/usr/local/bin/rsync-servers'
      mode: '0755'
    - src: 'rsync-servers-shell.j2'
      dest: '/usr/local/bin/rsync-servers-shell'
      mode: '0755'
  when: (container_image_pull.changed)
  notify: 'Reload systemd daemon'
  tags: ['never', 'containers-update']

- name: 'Disable rsync-servers timer'
  ansible.builtin.systemd_service:
    name: 'rsync-servers.timer'
    enabled: false
  tags: ['never', 'containers-disable']

- name: 'Stop rsync-servers timer'
  ansible.builtin.systemd_service:
    name: 'rsync-servers.timer'
    state: 'stopped'
  tags: ['never', 'containers-stop']

- name: 'Enable rsync-servers timer'
  ansible.builtin.systemd_service:
    name: 'rsync-servers.timer'
    enabled: true
  tags: ['never', 'containers-enable']

- name: 'Start rsync-servers timer'
  ansible.builtin.systemd_service:
    name: 'rsync-servers.timer'
    state: 'started'
  tags: ['never', 'containers-start']
