---
containers_images_tags:
  cockpit: 'latest'
  sshd_rsync: 'latest'
  rsync_servers: 'latest'
  mbsync: '1.5.0'
  vdirsyncer: 'latest'
  borgmatic: '2.0'
  autorestic: '1.8'
  cetusguard: 'v1'
  traefik: '3'
  uptime_kuma: '1'
  healthchecks:
    postgres: '16'
    server: 'v3.10'
  prometheus: 'latest'
  loki: 'latest'
  syslog_ng: 'latest'
  grafana: 'latest'
  node_exporter: 'latest'
  systemd_exporter: 'latest'
  promtail: 'latest'
  home_assistant: 'stable'
  nextcloud:
    postgres: '16'
    redis: '7'
    server: '31-fpm'
    nginx: '1'
  collabora_online: 'latest'
  stirling_pdf: 'latest-ultra-lite'
  immich:
    postgres: '16-vectorchord0.4.3'
    valkey: '8'
    machine_learning: 'release'
    server: 'release'
  ttrss:
    postgres: '16'
    server: 'latest'
    nginx: 'latest'
  freshrss: 'latest'
  it_tools: 'latest'
  plex: 'latest'
  tautulli: 'latest'
  navidrome: 'latest'
  calibre: 'latest'
  calibre_web: 'latest'
  komga: 'latest'
  gluetun: 'latest'
  transmission: 'latest'
  sabnzbd: 'latest'
  flaresolverr: 'latest'
  unpackerr: '0'
  recyclarr: '7'
  prowlarr: 'latest'
  radarr: 'latest'
  sonarr: 'latest'
  bazarr: 'latest'
  lidarr: 'latest'
  readarr: 'develop'
  mylar: 'latest'
  overseerr: 'latest'
  maintainerr: 'latest'
