---
- name: 'Create/Update Collabora Online CNAME record'
  community.general.cloudflare_dns:
    api_token: '{{ cloudflare_dns_token }}'
    zone: '{{ domain_name }}'
    record: 'office'
    ttl: 3600
    type: 'CNAME'
    value: '{{ ansible_facts["fqdn"] }}'
    proxied: false
    state: 'present'
  delegate_to: 'localhost'

- name: 'Create Collabora Online env bind mount path'
  ansible.builtin.file:
    path: '{{ containers_storage_path }}/env/collabora-online'
    owner: 'root'
    group: 'root'
    mode: '0700'
    state: 'directory'

- name: 'Create Collabora Online environment file'
  ansible.builtin.copy:
    content: |
      username={{ collabora_online.user }}
      password={{ collabora_online.password }}
    dest: '{{ containers_storage_path }}/env/collabora-online/collabora-online.env'
    owner: 'root'
    group: 'root'
    mode: '0400'
  register: 'environment_file'

- name: 'Create Collabora Online quadlet unit from template'
  ansible.builtin.template:
    src: 'collabora-online.container.j2'
    dest: '/etc/containers/systemd/collabora-online.container'
    owner: 'root'
    group: 'root'
    mode: '0644'
  register: 'quadlet_unit'
  notify: 'Reload systemd daemon'

- name: 'Enable and start Collabora Online container'
  ansible.builtin.systemd_service:
    name: 'collabora-online.service'
    daemon_reload: true
    enabled: true
    state: 'started'
  register: 'systemd_start'

- name: 'Restart Collabora Online service if environment file or quadlet unit has changed while service was already started'
  ansible.builtin.systemd_service:
    name: 'collabora-online.service'
    daemon_reload: true
    state: 'restarted'
  when: ((environment_file.changed or quadlet_unit.changed) and not systemd_start.changed)
