---
- name: 'Create changedetection data bind mount path'
  ansible.builtin.file:
    path: '{{ containers_storage_path }}/data/changedetection'
    owner: 'root'
    group: 'root'
    mode: '0700'
    state: 'directory'

- name: 'Create changedetection quadlet unit from template'
  ansible.builtin.template:
    src: 'changedetection.container.j2'
    dest: '/etc/containers/systemd/changedetection.container'
    owner: 'root'
    group: 'root'
    mode: '0644'
  register: 'quadlet_unit'
  notify: 'Reload systemd daemon'

- name: 'Enable and start changedetection container'
  ansible.builtin.systemd_service:
    name: 'changedetection.service'
    daemon_reload: true
    enabled: true
    state: 'started'
  register: 'systemd_start'

- name: 'Restart changedetection service if quadlet unit has changed while service was already started'
  ansible.builtin.systemd_service:
    name: 'changedetection.service'
    daemon_reload: true
    state: 'restarted'
  when: (quadlet_unit.changed and not systemd_start.changed)
