---
# This is kind of an ugly workaround for an issue having to do with systemd-resolved and/or podman/netavark/aardvark-dns.
# Starting with Fedora 41, some of the containers could'nt resolve the FQDN of the host its running on.
# After investigating, I realised that systemd-resolved adds all the local ip addresses as answers if a client try to resolve the local hostname.
# Because podman creates a lot of interfaces, and with IPv6 you get 2 IPv6 address per podman/veth interface (ULA and link-local), the answer to
# the query `dig AAAA host.domain.tld` contains a crap ton of IP on some of my hosts.
# Resolving the hostname from the host doesn't exhibit the issue, that's why I'm not 100% certain that systemd-resolved is the culprit. I also
# don't know if systemd-resolved local hostname resolution behavior is new or not.
# resovled.conf doesn't have a parameter to disable local hostname resolution or to limit the scope of the answer so I found a workaround to the
# problem in forcing the local hostname resolution to the host "principal" ip address by adding it to the hosts file. That way systemd-resolved
# only returns those addresses.
- name: 'Add local hostname to hosts file'
  ansible.builtin.template:
    src: 'hosts.j2'
    dest: '/etc/hosts'
    owner: 'root'
    group: 'root'
    mode: '0644'
