---
- name: 'Create/Update Home Assistant CNAME record'
  community.general.cloudflare_dns:
    api_token: '{{ cloudflare_dns_token }}'
    zone: '{{ domain_name }}'
    record: 'home'
    ttl: 3600
    type: 'CNAME'
    value: '{{ ansible_fqdn }}'
    proxied: false
    state: 'present'
  delegate_to: 'localhost'

- name: 'Create Home Assistant data bind mount path'
  ansible.builtin.file:
    path: '{{ containers_storage_path }}/data/home-assistant'
    owner: 'root'
    group: 'root'
    mode: '0700'
    state: 'directory'

- name: 'Create Home Assistant quadlet unit from template'
  ansible.builtin.template:
    src: 'home-assistant.container.j2'
    dest: '/etc/containers/systemd/home-assistant.container'
    owner: 'root'
    group: 'root'
    mode: '0644'
  register: 'quadlet_unit'
  notify: 'Reload systemd daemon'

- name: 'Enable and start Home Assistant container'
  ansible.builtin.systemd_service:
    name: 'home-assistant.service'
    daemon_reload: true
    enabled: true
    state: 'started'
  register: 'systemd_start'

- name: 'Restart Home Assistant service if quadlet unit has changed while service was already started'
  ansible.builtin.systemd_service:
    name: 'home-assistant.service'
    daemon_reload: true
    state: 'restarted'
  when: (quadlet_unit.changed and not systemd_start.changed)

- name: 'Add Traefik container network to Home Assistant trusted proxies'
  block:
    - name: 'Get podman networks info'
      containers.podman.podman_network_info:
        name: 'traefik-external'
      register: 'podman_network'

    - name: 'Authorize reverse proxy in configuration file'
      ansible.builtin.blockinfile:
        path: '{{ containers_storage_path }}/data/home-assistant/configuration.yaml'
        block: |
          http:
            use_x_forwarded_for: true
            trusted_proxies:
          {% for subnet in podman_network | community.general.json_query("networks[*].subnets[*].subnet") | ansible.builtin.flatten %}
              - {{ subnet }}
          {% endfor %}
      notify: 'Restart home-assistant service'
