---
# See https://forum.proxmox.com/threads/e1000-driver-hang.58284/page-7#post-368615
- name: 'Disable HW segmentation offload on Intel ethernet network interfaces'
  ansible.builtin.lineinfile:
    path: '/etc/network/interfaces'
    regexp: '^	post-up ethtool -K {{ item }}'
    line: '	post-up ethtool -K {{ item }} gso off tso off'
    insertafter: '^iface {{ item }} inet'
    state: 'present'
  loop: '{{ ansible_facts["interfaces"] }}'
  when:
    - (ansible_facts[item].module is defined and ansible_facts[item].module == "e1000e")
    - (ansible_facts[item].features.generic_segmentation_offload == "on" or ansible_facts[item].features.tcp_segmentation_offload == "on")
  notify: 'Restart networking service'
