---
- name: 'Create/Update Plex CNAME record'
  community.general.cloudflare_dns:
    api_token: '{{ cloudflare_dns_token }}'
    zone: '{{ domain_name }}'
    record: 'plex'
    ttl: 3600
    type: 'CNAME'
    value: '{{ ansible_fqdn }}'
    proxied: false
    state: 'present'
  delegate_to: 'localhost'

- name: 'Create Plex network'
  containers.podman.podman_network:
    name: 'plex-external'
    internal: false
    ipv6: '{{ containers_ipv6.enable }}'
    # See https://github.com/containers/netavark/issues/709
    # opt:
    #   isolate: true

- name: 'Add Plex network to firewalld trusted zone'
  block:
    - name: 'Get podman networks info'
      containers.podman.podman_network_info:
        name: 'plex-external'
      register: 'podman_network'

    - name: 'Add podman networks subnets to firewalld trusted zone'
      ansible.posix.firewalld:
        source: '{{ item }}'
        zone: 'trusted'
        permanent: true
        immediate: true
        state: 'enabled'
      loop: '{{ podman_network | community.general.json_query("networks[*].subnets[*].subnet") | ansible.builtin.flatten }}'

- name: 'Accept Plex incomming connections in default firewalld zone'
  ansible.posix.firewalld:
    service: 'plex'
    permanent: true
    immediate: true
    state: 'enabled'

- name: 'Create Plex bind mounts paths'
  ansible.builtin.file:
    path: '{{ containers_storage_path }}/{{ item }}'
    owner: 1000
    group: 1000
    mode: '0700'
    state: 'directory'
  loop:
    - 'data/plex'
    - 'runtime/plex'

- name: 'Create Plex quadlet unit from template'
  ansible.builtin.template:
    src: 'plex.container.j2'
    dest: '/etc/containers/systemd/plex.container'
    owner: 'root'
    group: 'root'
    mode: '0644'
  register: 'quadlet_unit'
  notify: 'Reload systemd daemon'

- name: 'Enable and start Plex container'
  ansible.builtin.systemd:
    name: 'plex.service'
    daemon_reload: true
    enabled: true
    state: 'started'
  register: 'systemd_start'

- name: 'Restart Plex service if quadlet unit has changed while service was already started'
  ansible.builtin.systemd:
    name: 'plex.service'
    daemon_reload: true
    state: 'restarted'
  when: (quadlet_unit.changed and not systemd_start.changed)
