---
- name: 'Create/Update Calibre-Web CNAME record'
  community.general.cloudflare_dns:
    api_token: '{{ cloudflare_dns_token }}'
    zone: '{{ domain_name }}'
    record: 'calibre-web'
    ttl: 3600
    type: 'CNAME'
    value: '{{ ansible_facts["fqdn"] }}'
    proxied: false
    state: 'present'
  delegate_to: 'localhost'

- name: 'Create Calibre-Web data bind mount path'
  ansible.builtin.file:
    path: '{{ containers_storage_path }}/data/calibre-web'
    owner: 911
    group: 911
    mode: '0700'
    state: 'directory'

- name: 'Create Calibre-Web quadlet unit from template'
  ansible.builtin.template:
    src: 'calibre-web.container.j2'
    dest: '/etc/containers/systemd/calibre-web.container'
    owner: 'root'
    group: 'root'
    mode: '0644'
  register: 'quadlet_unit'
  notify: 'Reload systemd daemon'

- name: 'Enable and start Calibre-Web container'
  ansible.builtin.systemd_service:
    name: 'calibre-web.service'
    daemon_reload: true
    enabled: true
    state: 'started'
  register: 'systemd_start'

- name: 'Restart Calibre-Web service if quadlet unit has changed while service was already started'
  ansible.builtin.systemd_service:
    name: 'calibre-web.service'
    daemon_reload: true
    state: 'restarted'
  when: (quadlet_unit.changed and not systemd_start.changed)
